--
--	DESTROY TABLE IF EXIST (RESET)
--

DROP TABLE IF EXISTS EMPLOYEE;


--
--	CREATE TABLE EMPLOYEE
--

CREATE TABLE EMPLOYEE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  SURNAME VARCHAR(250) NOT NULL,
  BIRTHDATE DATE NOT NULL,
  SALARY DECIMAL(12,2) NOT NULL
);
